# tasks file for fail2ban
---
- name: install
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ fail2ban_dependencies }}"
  tags:
    - configuration
    - fail2ban
    - fail2ban-install

- name: update configuration file - /etc/fail2ban/fail2ban.local
  template:
    src: etc/fail2ban/fail2ban.local.j2
    dest: /etc/fail2ban/fail2ban.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-configuration

- name: update configuration file - /etc/fail2ban/jail.local
  template:
    src: etc/fail2ban/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-configuration

- name: add/ update filters
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ fail2ban_filter_paths }}"
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-filters

- name: copy actions
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ fail2ban_action_paths }}"
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-actions

- name: copy jails
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }"
    owner: root
    group: root
    mode: 0644
  with_dict: "{{ fail2ban_jail_paths }}"
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-jails

- name: start and enable service
  service:
    name: fail2ban
    state: started
    enabled: true
  tags:
    - configuration
    - fail2ban
    - fail2ban-start-enable-service
